// prepare.js — inlines phone.html, manifest, and icon assets into embedded.js
// so pkg can bundle them reliably via require() tracing (no pkg.assets needed).

const fs = require('fs');
const path = require('path');

console.log('  [ .. ] Reading source files...');

const phoneHtml = fs.readFileSync(path.join(__dirname, 'phone.html'), 'utf8');
const manifest = fs.readFileSync(path.join(__dirname, 'manifest.webmanifest'), 'utf8');

// Embed icon files as base64 — these get decoded back to Buffer at runtime
const assetsDir = path.join(__dirname, 'assets');
const iconFiles = ['apple-touch-icon.png', 'icon-192.png', 'icon-512.png'];
const assets = {};
let totalAssetBytes = 0;
for (const file of iconFiles) {
  const filePath = path.join(assetsDir, file);
  if (fs.existsSync(filePath)) {
    const data = fs.readFileSync(filePath);
    assets[file] = data.toString('base64');
    totalAssetBytes += data.length;
  }
}

const output = `// Auto-generated by prepare.js  -  DO NOT EDIT BY HAND.
// All static assets are inlined here so pkg traces them via require()
// and bundles them reliably into PhoneBridge.exe.

module.exports = {
  PHONE_HTML: ${JSON.stringify(phoneHtml)},
  MANIFEST: ${JSON.stringify(manifest)},
  ASSETS: {
${Object.entries(assets).map(([name, b64]) => `    ${JSON.stringify(name)}: Buffer.from(${JSON.stringify(b64)}, 'base64')`).join(',\n')}
  }
};
`;

fs.writeFileSync(path.join(__dirname, 'embedded.js'), output);
console.log('  [ ok ] embedded.js written (' + Math.round(output.length / 1024) + ' KB total)');
console.log('         - phone.html:           ' + phoneHtml.length + ' chars');
console.log('         - manifest.webmanifest: ' + manifest.length + ' chars');
console.log('         - icon assets:          ' + Object.keys(assets).length + ' files, ' + totalAssetBytes + ' bytes');
