// PhoneBridge — terminal-native phone-to-PC bridge
// by PskXClaude

const http = require('http');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { execSync } = require('child_process');
const QRCode = require('qrcode');

process.title = 'PhoneBridge';

const PORT = 9147;
const state = { clipboard: '', files: [], links: [], events: [] };

// ---------- IP detection ----------
function getLocalIPs() {
  const ifaces = os.networkInterfaces();
  const candidates = [];
  for (const [name, addrs] of Object.entries(ifaces)) {
    for (const addr of addrs) {
      // family is 'IPv4' (Node 18+) but was the number 4 in a few releases — accept both.
      if (addr.family !== 'IPv4' && addr.family !== 4) continue;
      if (addr.internal) continue;
      const ip = addr.address;
      // Reject junk/non-routable addresses some VPN/virtual adapters report.
      if (!ip || ip === '0.0.0.0' || ip.startsWith('0.') ||
          ip.startsWith('127.') || ip.startsWith('169.254.')) continue;

      const lower = name.toLowerCase();
      // Skip virtual machine, container, and VPN adapters by name.
      if (lower.match(/virtualbox|vmware|hyper-?v|vethernet|loopback|docker|tailscale|zerotier|hamachi|radmin|openvpn|wireguard|nordlynx|\bvpn\b|\btap\b|\btun\b|\bwg\d*\b|\bzt\b|npcap|bluetooth/)) continue;

      let score = 0;
      if (ip.startsWith('192.168.')) score = 100;                       // most home LANs
      else if (ip.startsWith('10.')) score = 80;                        // private
      else if (/^172\.(1[6-9]|2\d|3[01])\./.test(ip)) score = 60;       // private 172.16-31
      else score = 10;                                                  // other/routable — last resort
      if (lower.match(/wi-?fi|wlan|wireless/)) score += 50;
      else if (lower.match(/ethernet|eth|\blan\b/)) score += 30;
      candidates.push({ name, address: ip, score });
    }
  }
  candidates.sort((a, b) => b.score - a.score);
  return candidates;
}

// ---------- Activity log ----------
function timestamp() {
  const d = new Date();
  const pad = n => String(n).padStart(2, '0');
  return `${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}

function logEvent(type, title, sub) {
  const evt = { type, title, sub, time: Date.now() };
  state.events.unshift(evt);
  if (state.events.length > 50) state.events.pop();
  const typeLabel = type.toUpperCase().padEnd(9);
  let line = `  [${timestamp()}]  ${typeLabel}  ::  ${title}`;
  if (sub) line += `  ::  ${sub}`;
  console.log(line);
}

// ---------- Embedded assets ----------
// In production, embedded.js is generated by prepare.js (run by Build.bat).
// pkg auto-traces this require() and bundles embedded.js into the .exe.
// In dev (node server.js without prepare), fall back to reading source files.
let PHONE_HTML, MANIFEST, EMBEDDED_ASSETS;
try {
  const embedded = require('./embedded.js');
  PHONE_HTML = embedded.PHONE_HTML;
  MANIFEST = embedded.MANIFEST;
  EMBEDDED_ASSETS = embedded.ASSETS || {};
} catch (e) {
  PHONE_HTML = fs.readFileSync(path.join(__dirname, 'phone.html'), 'utf8');
  MANIFEST = fs.readFileSync(path.join(__dirname, 'manifest.webmanifest'), 'utf8');
  EMBEDDED_ASSETS = {};
}

// ---------- HTTP server ----------
function startServer() {
  const server = http.createServer((req, res) => {
    const url = new URL(req.url, `http://${req.headers.host}`);
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    if (req.method === 'OPTIONS') { res.writeHead(204); return res.end(); }

    if (req.method === 'GET' && (url.pathname === '/' || url.pathname === '/index.html')) {
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      return res.end(PHONE_HTML);
    }

    if (req.method === 'GET' && url.pathname === '/manifest.webmanifest') {
      res.writeHead(200, { 'Content-Type': 'application/manifest+json' });
      return res.end(MANIFEST);
    }

    if (req.method === 'GET' && url.pathname.startsWith('/assets/')) {
      const fname = url.pathname.slice('/assets/'.length);
      const contentType = fname.endsWith('.ico') ? 'image/x-icon' : 'image/png';
      // Embedded version (in built .exe)
      if (EMBEDDED_ASSETS[fname]) {
        res.writeHead(200, { 'Content-Type': contentType, 'Cache-Control': 'public, max-age=86400' });
        return res.end(EMBEDDED_ASSETS[fname]);
      }
      // Disk version (dev mode)
      const filePath = path.join(__dirname, url.pathname);
      if (fs.existsSync(filePath)) {
        res.writeHead(200, { 'Content-Type': contentType, 'Cache-Control': 'public, max-age=86400' });
        return res.end(fs.readFileSync(filePath));
      }
      res.writeHead(404); return res.end();
    }

    if (req.method === 'GET' && url.pathname === '/state') {
      res.writeHead(200, { 'Content-Type': 'application/json' });
      return res.end(JSON.stringify({
        clipboard: state.clipboard,
        files: state.files.map(f => ({ name: f.name, size: f.size, time: f.time })),
        links: state.links
      }));
    }

    if (req.method === 'POST' && url.pathname === '/clipboard') {
      let body = '';
      req.on('data', d => body += d);
      req.on('end', () => {
        try { state.clipboard = JSON.parse(body).text || ''; } catch { state.clipboard = body; }
        try {
          const tmp = path.join(os.tmpdir(), 'phonebridge_clip.txt');
          fs.writeFileSync(tmp, state.clipboard, 'utf8');
          execSync(`powershell -Command "Get-Content -Raw '${tmp}' | Set-Clipboard"`, { stdio: 'ignore' });
        } catch (e) {}
        const preview = state.clipboard.length > 60
          ? state.clipboard.slice(0, 57) + '...'
          : state.clipboard;
        logEvent('clipboard', preview);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: true }));
      });
      return;
    }

    if (req.method === 'POST' && url.pathname === '/link') {
      let body = '';
      req.on('data', d => body += d);
      req.on('end', () => {
        try {
          const { url: link, title } = JSON.parse(body);
          state.links.unshift({ url: link, title: title || link, time: Date.now() });
          if (state.links.length > 20) state.links.pop();
          logEvent('link', title || link, link);
          res.writeHead(200, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ ok: true }));
        } catch { res.writeHead(400); res.end('bad'); }
      });
      return;
    }

    if (req.method === 'POST' && url.pathname === '/file') {
      let chunks = [];
      req.on('data', d => chunks.push(d));
      req.on('end', () => {
        try {
          const raw = Buffer.concat(chunks);
          const boundary = (req.headers['content-type'] || '').split('boundary=')[1];
          if (!boundary) { res.writeHead(400); return res.end('no boundary'); }
          const bBuf = Buffer.from('--' + boundary);
          let start = raw.indexOf(bBuf) + bBuf.length + 2;
          const headerEnd = raw.indexOf('\r\n\r\n', start);
          const header = raw.slice(start, headerEnd).toString();
          const nameMatch = header.match(/filename="([^"]+)"/);
          const fname = nameMatch ? nameMatch[1] : `file_${Date.now()}`;
          const fileData = raw.slice(headerEnd + 4, raw.lastIndexOf('\r\n--' + boundary));

          const outDir = path.join(os.homedir(), 'Downloads', 'PhoneBridge');
          if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
          const outPath = path.join(outDir, fname);
          fs.writeFileSync(outPath, fileData);
          state.files.unshift({ name: fname, size: fileData.length, time: Date.now(), path: outPath });
          if (state.files.length > 20) state.files.pop();
          const sizeStr = fileData.length < 1024 ? `${fileData.length}B`
            : fileData.length < 1048576 ? `${(fileData.length/1024).toFixed(1)}KB`
            : `${(fileData.length/1048576).toFixed(1)}MB`;
          logEvent('file', fname, `${sizeStr}  >>  Downloads/PhoneBridge`);
          res.writeHead(200, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ ok: true, path: outPath }));
        } catch (e) {
          res.writeHead(500); res.end('error');
        }
      });
      return;
    }

    res.writeHead(404); res.end('not found');
  });

  return new Promise((resolve, reject) => {
    server.listen(PORT, '0.0.0.0', resolve);
    server.on('error', reject);
  });
}

// ---------- Banner ----------
function printBanner() {
  console.log('');
  console.log(' .----------------------------------------------------------.');
  console.log(' | [ PHONEBRIDGE.SYS ]                           [ * ONLINE ] |');
  console.log(' :----------------------------------------------------------:');
  console.log(' |                                                          |');
  console.log(' |             /---\\  |   |  /---\\  |\\  |  /----             |');
  console.log(' |             |   |  |   |  |   |  | \\ |  |                 |');
  console.log(' |             |---/  |---|  |   |  |  \\|  |----             |');
  console.log(' |             |      |   |  |   |  |   |  |                 |');
  console.log(' |             |      |   |  \\---/  |   |  \\----             |');
  console.log(' |                                                          |');
  console.log(' |         /---\\  /---\\  |---|  |---\\  /---\\  /----            |');
  console.log(' |         |   |  |   |    |    |   |  |      |                |');
  console.log(' |         |---/  |---/    |    |   |  | --\\  |----            |');
  console.log(' |         |   \\  |  \\     |    |   |  |   |  |                |');
  console.log(' |         \\---/  |   \\  |---|  |---/  \\---/  \\----            |');
  console.log(' |                                                          |');
  console.log(' |                  :: by PskXClaude ::                       |');
  console.log(' |                                                          |');
  console.log(' :----------------------------------------------------------:');
  console.log(' | KEY :: 0xAF.C9.7E.12       PORT :: 9147       PROTO :: AES |');
  console.log(' \'----------------------------------------------------------\'');
  console.log('');
}

// ---------- Boot sequence ----------
async function boot() {
  console.clear();
  printBanner();

  console.log('    ~> 7F.4A.E9.C1  ::  PACKET 001  ::  HANDSHAKE OK  ::  200');
  console.log('');

  console.log('    > probing local interfaces ............... [  OK  ]');
  const ips = getLocalIPs();
  if (ips.length === 0) {
    console.log('');
    console.log('    [ FAIL ]  Couldn\'t find your local network address.');
    console.log('              1. Make sure this PC is connected to Wi-Fi or Ethernet.');
    console.log('              2. Or find it by hand: open Command Prompt and run  ipconfig');
    console.log('                 Use the "IPv4 Address" (looks like 192.168.x.x), then on');
    console.log('                 your phone open  http://THAT-ADDRESS:' + PORT);
    console.log('');
    return;
  }

  console.log('    > spawning HTTP listener on :' + PORT + ' .......... [  OK  ]');
  try {
    await startServer();
  } catch (e) {
    console.log('    [ FAIL ]  Port ' + PORT + ' is already in use.');
    console.log('              Close any other PhoneBridge instance and try again.');
    return;
  }

  const url = `http://${ips[0].address}:${PORT}`;
  console.log('    > generating QR token .................... [  OK  ]');
  console.log('    > establishing bridge daemon ............. [  OK  ]');
  console.log('');
  console.log('       [ READY ]  bridge active on ' + url);
  console.log('');
  console.log('       SCAN WITH YOUR IPHONE CAMERA:');
  console.log('');

  // Generate and print QR
  try {
    const qr = await QRCode.toString(url, { type: 'terminal', small: true });
    // Indent each line of the QR
    const indented = qr.split('\n').map(l => '       ' + l).join('\n');
    console.log(indented);
  } catch (e) {
    console.log('       (QR render failed — open the URL on your phone manually)');
  }

  console.log('       Or open in iPhone Safari: ' + url);
  console.log('       Tip: Share -> Add to Home Screen for an app icon');
  if (ips.length > 1) {
    console.log('');
    console.log('       Phone can\'t connect? Your PC has more than one network');
    console.log('       adapter — try one of these addresses instead:');
    for (const c of ips) {
      console.log('         http://' + c.address + ':' + PORT + '   (' + c.name + ')');
    }
  }
  console.log('');
  console.log(' :==========================================================:');
  console.log(' |                     LIVE ACTIVITY                         |');
  console.log(' :==========================================================:');
  console.log('');
  console.log('  Waiting for phone... incoming events will appear below.');
  console.log('  Press Ctrl+C to stop.');
  console.log('');
}

boot().catch(e => {
  console.error('PhoneBridge crashed:', e);
  console.error('Press any key to close...');
});

process.on('SIGINT', () => {
  console.log('');
  console.log('  > PhoneBridge shutting down. Goodbye.');
  process.exit(0);
});
